# ⚠ Do NOT commit real secrets. Use sealed-secrets in production.
apiVersion: v1
kind: Secret
metadata:
  name: homely-secret
  namespace: homely
type: Opaque
data:
  JWT_SECRET: c3VwZXJfc2VjcmV0X2hvbWVseV9rZXlfMjAyNg==
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9rcmFudGNtZl9kYl91c2VyOjdEMW9hZGc2YTBDUEZnNkFAaG9tZWx5YXRsYXMucXp1aWpqaC5tb25nb2RiLm5ldC9ob21lbHk/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9SG9tZWx5YXRsYXM=
